package com.course.tasksapi.model;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

/**
 * A single task — the one and only domain object in this API.
 *
 * <p>Shape (PRD §8.2):
 * <pre>
 *   { "id": uuid, "title": str, "description": str?, "done": false, "createdAt": ISO-8601 }
 * </pre>
 *
 * <p>This is a plain mutable POJO with a no-arg constructor and getters/setters
 * so Jackson can serialize/deserialize it, and so the PUT handler can update
 * fields in place. {@code id} and {@code createdAt} are generated by the server
 * (see {@link #create}), never accepted from the client.
 */
public class Task {

    private String id;
    private String title;
    private String description; // optional
    private boolean done;
    private String createdAt;   // ISO-8601 UTC string, e.g. "2026-06-14T12:00:00Z"

    /** Required by Jackson and by the DynamoDB mapper used later. */
    public Task() {
    }

    /**
     * Factory for a brand-new task: generates the id and timestamp and defaults
     * {@code done} to false. Use this for POST /tasks rather than trusting client
     * input for server-controlled fields.
     */
    public static Task create(String title, String description) {
        Task t = new Task();
        t.id = UUID.randomUUID().toString();
        t.title = title;
        t.description = description;
        t.done = false;
        // Truncate to whole seconds so the timestamp reads like the PRD example
        // ("...T12:00:00Z") instead of carrying nanoseconds.
        t.createdAt = Instant.now().truncatedTo(ChronoUnit.SECONDS).toString();
        return t;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isDone() {
        return done;
    }

    public void setDone(boolean done) {
        this.done = done;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
}
